name: Publish to Citronus PyPI

on:
  workflow_dispatch:

env:
  FORCE_COLOR: 1

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: citronus-pypi
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v5

      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish --publish-url https://pypi.citronus.pro
        env:
          UV_PUBLISH_USERNAME: ${{ secrets.PYPI_USERNAME }}
          UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

      - name: Echo password
        run: echo ${{ secrets.PYPI_PASSWORD }} ${{ secrets.PYPI_USERNAME }}